version: "3.8"

services:
  topor-service:
    container_name: topor-container
    build: .
    image: topor-image
    volumes:
      - ./:/app
    ports:
      - "8000:8242"


  jenkins-service:
    container_name: jenkins-container
    build: ./jenkins
    image: jenkins-image
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - topor-service

volumes:
  jenkins_home: